version: '3.4'

services:
  Plant-Backend:
    image: plant
    build:
      context: back-end/Plant-Project-Backend
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "5000:5000"
